apiVersion: 1

datasources:
  - name: JARVIS-PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    database: jarvis
    user: jarvis_admin
    secureJsonData:
      password: 'W!@#wps@2026'
    jsonData:
      sslmode: disable
      maxOpenConns: 5
      maxIdleConns: 2
      connMaxLifetime: 14400
      postgresVersion: 1600
      timescaledb: false
    isDefault: true
    editable: true
